apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.common.name }}
  namespace: {{ .Values.common.namespace }}
spec:
  port:
    targetPort: http-grafana
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: {{ .Values.common.name }}
    weight: 100
  wildcardPolicy: None