apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ .Values.common.name }}
  name: grafana-token
  namespace: {{ .Values.common.namespace }}
type: kubernetes.io/service-account-token